<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoomReservation.Common\RoomReservation.Common.csproj" />
    <ProjectReference Include="..\RoomReservation.Data\RoomReservation.Data.csproj" />
    <ProjectReference Include="..\RoomReservation.Domain\RoomReservation.Domain.csproj" />
  </ItemGroup>

</Project>
